CREATE OR REPLACE TRIGGER my_trigger
BEFORE INSERT OR DELETE OR UPDATE ON ETUDIANT
FOR EACH ROW
BEGIN
    IF UPDATING THEN
            DBMS_OUTPUT.PUT_LINE("MSG 1");
    ELSIF DELETING THEN
            DBMS_OUTPUT.PUT_LINE("MSG 2");
    ELSIF INSERTING THEN 
        DBMS_OUTPUT.PUT_LINE("MSG 3");
    END IF;
END;/
